language: java
sudo: false # faster builds

jdk:
  - oraclejdk8

install: travis_wait mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
  - bash <(curl -s https://codecov.io/bash)
