language: java
sudo: false # faster builds

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

install:
  - ./mvnw dependency:purge-local-repository

script: 
  - ./mvnw clean install

after_success:
  - bash <(curl -s https://codecov.io/bash)
